export const getSvg = (type) => {
  switch (type) {
    case 'close':
      return require('./svg/close.svg');
    case 'bell':
      return require('./svg/bell.svg');
    case 'calendar-o':
      return require('./svg/calendar-o.svg');
    case 'close':
      return require('./svg/close.svg');
    case 'calendar':
      return require('./svg/calendar.svg');
    case 'change':
      return require('./svg/change.svg');
    case 'copy':
      return require('./svg/copy.svg');
    case 'download':
      return require('./svg/download.svg');
    case 'envelope':
      return require('./svg/envelope.svg');
    case 'eyeclose':
      return require('./svg/eyeclose.svg');
    case 'eyeopen':
      return require('./svg/eyeopen.svg');
    case 'folder':
      return require('./svg/folder.svg');
    case 'help':
      return require('./svg/help.svg');
    case 'home':
      return require('./svg/home.svg');
    case 'move':
      return require('./svg/move.svg');
    case 'next':
      return require('./svg/next.svg');
    case 'pdf':
      return require('./svg/pdf.svg');
    case 'pencil':
      return require('./svg/pencil.svg');
    case 'ppt':
      return require('./svg/ppt.svg');
    case 'print':
      return require('./svg/print.svg');
    case 'refresh-o':
      return require('./svg/refresh-o.svg');
    case 'refresh':
      return require('./svg/refresh.svg');
    case 'remove':
      return require('./svg/remove.svg');
    case 'search-o':
      return require('./svg/search-o.svg');
    case 'search':
      return require('./svg/search.svg');
    case 'setting':
      return require('./svg/setting.svg');
    case 'uparrow':
      return require('./svg/uparrow.svg');
    case 'word':
      return require('./svg/word.svg');
    case 'zml':
      return require('./svg/zml.svg');
    default:
      return null;
  }
}
