import ReactDom from 'react-dom';
import React from 'react';
import  { Icon } from './index';
ReactDom.render([
  <Icon type='close' />,
  <Icon type='bell' />,
  // <Icon type='calendar-o' />,
  // <Icon type='close' />,
  // <Icon type='calendar' />,
  // <Icon type='change' />,
  // <Icon type='copy' />,
  // <Icon type='download' />,
  // <Icon type='envelope' />,
  // <Icon type='eyeclose' />,
  // <Icon type='eyeopen' />,
  // <Icon type='folder' />,
  // <Icon type='help' />,
  // <Icon type='home' />,
  // <Icon type='move' />,
  // <Icon type='next' />,
  // <Icon type='pdf' />,
  // <Icon type='pencil' />,
  // <Icon type='ppt' />,
  // <Icon type='print' />,
  // <Icon type='refresh-o' />,
  // <Icon type='refresh' />,
  // <Icon type='remove' />,
  // <Icon type='search-o' />,
  // <Icon type='search' />,
  // <Icon type='setting' />,
  // <Icon type='uparrow' />,
  // <Icon type='word' />,
  // <Icon type='zml' />,
], document.body);
